apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
spec:
  containers:
  - name: demo
    image: nginx
    env:
    - name: PROXY_STATUS # Notice that the case is different here
      valueFrom:
        configMapKeyRef:
          name: proxy-config           # The ConfigMap this value comes from.
          key: proxy-status
