apiVersion: v1
kind: ResourceQuota
metadata:
  name: objects-quota
spec:
  hard:
    count/deployments.apps: 2
    count/replicasets.apps: 10
    count/statefulsets.apps: 2
    count/jobs.batch: 10
    count/cronjobs.batch: 3
    replicationcontrollers: 5
    pods: 10
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 5
    services: 5
    services.loadbalancers: 1
    services.nodeports: 2
    ssd.storageclass.storage.k8s.io/persistentvolumeclaims: 2
