apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    name: wordpress-rs
  name: wordpress-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-rs-pod
  template:
    metadata:
      labels:
        app: wordpress-rs-pod
    spec:
      containers:
      - image: wordpress
        name: wordpress  

